### ISSUE TITLE
Doesn't support negative BigInt

### ISSUE THREAD

**Issue by imadassamani** [Ivan-Korolenko/json-with-bigint#4]
https://github.com/Ivan-Korolenko/json-with-bigint/blob/a93d7e4e0d52b5477d431a751b65f32d6182df78/json-with-bigint.js#L28

Based on this regex, negative numbers can't properly be parsed. I think using this would help to detect it (I added '-?')

```
const numbersBiggerThanMaxInt =
  /(?<=:|:\[|:\[.*)(-?\d{17,}|(?:[9](?:[1-9]07199254740991|0[1-9]7199254740991|00[8-9]199254740991|007[2-9]99254740991|007199[3-9]54740991|0071992[6-9]4740991|00719925[5-9]740991|007199254[8-9]40991|0071992547[5-9]0991|00719925474[1-9]991|00719925474099[2-9])))(?=[,\}\]])/g
```

**Comment by Ivan-Korolenko** [comment]
Hi @imadassamani, thank you for letting me know! This issue is now fixed in version **2.1.1**.

Feel free to create a new issue if you encounter any problems with the library in the future.
