### ISSUE TITLE
Parsing decimal number with too high precision

### ISSUE THREAD

**Issue by imadassamani** [Ivan-Korolenko/json-with-bigint#5]
When trying to parse a decimal with too high precision, the JSONParse breaks. 

Given the number 0.46153846153846156, it will be converted to 0."46153846153846156n" instead of "0.46153846153846156n", which causes the inner JSON.parse to fail

**Comment by Ivan-Korolenko** [comment]
Hi @imadassamani, thank you for letting me know! This issue is now fixed in version 2.1.2.

Feel free to create a new issue if you encounter any problems with the library in the future.
