### ISSUE TITLE
Null Object Parsing

### ISSUE THREAD

**Issue by imadassamani** [Ivan-Korolenko/json-with-bigint#6]
The JSONParse fail when using as a http response parser, whereby the server returns back an empty body 200 OK response. I think just a simple check for if json is null or undefined or blank string would be sufficient for this. Thanks a lot

**Comment by Ivan-Korolenko** [comment]
Hi @imadassamani. Please provide a code example that uses `JSONParse()` and the result of running it, so that I can understand the use case and what the issue is.

**Comment by imadassamani** [comment]
Hi. Nevermind, i think i found a way to do the null checking before calling the `JSONParse()`. Thanks a lot
