### ISSUE TITLE
[Feature Request] Space param of stringify

### ISSUE THREAD

**Issue by neko-para** [Ivan-Korolenko/json-with-bigint#8]
Add an extra param `space`, which just pass-through to JSON.stringify.

**Comment by Ivan-Korolenko** [comment]
Hi @neko-para,

Thank you for this feature request. **It's implemented in version 2.2.3** and already available on npm.

Thank you for your interest in the `json-with-bigin`t library. Feel free to create a new issue or a PR if you encounter any problems with the library in the future or if you would like to propose some feature or a change.
